apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: etcd
  name: etcd
  namespace: etcd-2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: etcd
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: etcd
    spec:
      containers:
      - image: quay.io/coreos/etcd:v2.3.8
        name: etcd
        resources:
          limits:
            memory: "3Gi"
            cpu: "0.25"
        ports:
          - containerPort: 4001
        env:
        - name: "HOST_IP"
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        args: 
        - "-name"
        - "etcd0"
        - "-advertise-client-urls"
        - "http://$(HOST_IP):2379,http://$(HOST_IP):4001"
        - "-listen-client-urls"
        - "http://0.0.0.0:2379,http://0.0.0.0:4001"
        - "-initial-advertise-peer-urls"
        - "http://$(HOST_IP):2380"
        - "-listen-peer-urls"
        - "http://0.0.0.0:2380"
        - "-initial-cluster-token"
        - "etcd-cluster-1"
        - "-initial-cluster"
        - "etcd0=http://$(HOST_IP):2380"
        - "-initial-cluster-state"
        - "new"
      terminationGracePeriodSeconds: 30
