apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: etcd
  name: etcd
  namespace: etcd-2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: etcd
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: etcd
    spec:
      containers:
      - image: quay.io/coreos/etcd:v2.3.8
        name: etcd
        resources:
          limits:
            memory: "3Gi"
            cpu: "0.25"
        ports:
        - containerPort: 4001
        - containerPort: 2380
        - containerPort: 2379
        env:
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: HOST_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP 
        - name: ETCD_NAME
          value: "$(POD_NAME)"
        - name: ETCD_ADVERTISE_CLIENT_URLS
          value: "http://$(HOST_IP):2379,http://$(HOST_IP):4001"
        - name: ETCD_LISTEN_CLIENT_URLS
          value: "http://0.0.0.0:2379,http://0.0.0.0:4001"
        - name: ETCD_INITIAL_ADVERTISE_PEER_URLS 
          value: "http://$(HOST_IP):2380"
        - name: ETCD_LISTEN_PEER_URLS
          value: "http://0.0.0.0:2380"
        - name: ETCD_INITIAL_CLUSTER
          value: "$(POD_NAME)=http://$(HOST_IP):2380"
        - name: ETCD_INITIAL_CLUSTER_TOKEN
          value: "$(POD_NAME)"
        - name: ETCD_INITIAL_CLUSTER_STATE
          value: "new"
      terminationGracePeriodSeconds: 30
